<template>
    <div class="tucausa">
        <img class="banner" :src="banner" alt="">
        <div class="header">
            <p class="is-size-3 has-text-weight-bold">Pokedex app</p>
            <a href="https://github.com/SoyTanMax/pokedex">See Github repo</a>
        </div>
        <p class="is-size-5 has-text-justified has-text-weight-medium spacing">A mobile app development project with SwiftUI.</p>
        <p class="is-size-5 has-text-weight-bold">About the app</p>
        <p class="is-size-6 has-text-justified spacing">Last June of 2021, some classmates and I had to deliver a SwiftUI app as a final project for our mobile app development class. At first, we thought that an app for checking out coffee recipes would be a great idea, but we realized that the requirements included the use of an API and Firebase or CoreData so we had to switch our focus. After some research, we found about pokeapi.co and everybody thought developing a pokedex would be a great idea. The main idea of the app was to search through the list of pokemons and create a list of favorites.</p>
        <p class="is-size-5 has-text-weight-bold">App's requirements</p>
        <p class="is-size-6 has-text-justified">Our app required the following specifications: </p>
        <li>The app had to be built using SwiftUI. </li>
        <li>Make use of an API. </li>
        <li>Make use of Firebase or CoreData. </li>
        <li>Eye-catching design. </li>
        <li>Use components seen in class. </li>
        <li>Add something new or not seen in class. </li>
        <br>
        <p class="is-size-5 has-text-weight-bold">Inspiration</p>
        <p class="is-size-6 has-text-justified spacing">We had a very little amount of time in order to finish the app, so getting picky with the designs was not a very smart move. That's why we decided to give life to someone else's idea. There were a lot of designs on Dribble that conveyed the same idea: a home page with the list of all pokemons and a detailed view of each one. We chose to use the designs made by Saepul Nahwan shown below. </p>
        <img class="image spacing" :src="image1" alt="">
        <p class="is-size-5 has-text-weight-bold">Development</p>
        <p class="is-size-6 has-text-justified">So, neither me or my classmates had built an app with SwiftUI, other than the other ones we built previously in class, of course, but they were not that complicated. From my understanding and what we learned through the course, I could tell there were a lot of similarities of building an app with SwiftUI and any other Javascript framework. </p><br>
        <p class="is-size-6 has-text-justified has-text-weight-bold">Component Usage</p>
        <p class="is-size-6 has-text-justified spacing">The first and maybe the most important similarity is the use of components and passing props. Just like in Vue.js or React.js, in SwiftUI you are able to create reusable components that can change by specifying its props. <br>A clear example of this is the homepage were all the pokemons are listed. Each "card" is a single component automatically generated by running a for loop through the list of pokemons. </p>
        <img class="image spacing" :src="image2" alt="">
        <p class="is-size-6 has-text-justified">For each pokemon in media.pokemon, an array which we loaded previously through the API, a PokemonCellView component is going to be displayed. This components receives the pokemon we are currently in and an object named media that contains a function used to change the background color depending on the pokemon type. These are the props that helped us change how each card looks depending on the pokemon of the first array (media.pokemon). <br>After you click the PokemonCellView component it directs you to the PokemonDetailView, which is the second screen shown in the designs before. This PokemonDetailView also receives the pokemon we are currently in, the media object and a default status of false to the property isFavorite. </p><br>
        <p class="is-size-6 has-text-justified has-text-weight-bold">Styling components</p>
        <p class="is-size-6 has-text-justified spacing">Unlike a Javascript framework, there's no such thing as CSS in SwiftUI. All the styling applied to components is in-line styling so to speak, since all the modifiers are written below the elements we are styling. </p>
        <img class="image spacing image3" :src="image3" alt="">

        <p class="is-size-6 has-text-justified has-text-weight-bold">Add to favorites function</p>
        <p class="is-size-6 has-text-justified spacing">One of the main features of this app is that you can save your favorite pokemons and rather than using the CoreData of the app to save them, we decided to use Firebase.  When the like button is pressed, the function below recieves the pokemon we are currently in and creates a struct of type Favorite (because all the data pushed to this collection has to be this type of struct) with the pokemon data and creates and document in the collection. </p>
        <img class="image spacing" :src="image4" alt="">
        <p class="is-size-6 has-text-justified spacing">The function below shows how we fetched the favorite pokemons once they are already in the collection. I find it a little bit easier fetching a collection from Firebase in SwiftUI than doing it in Javascript since you don't have to disect all the documents and run a for loop to map the collection. </p>
        <img class="image spacing" :src="image5" alt="">

        <p class="is-size-5 has-text-weight-bold spacing">Demo</p>
        <p class="is-size-6 has-text-justified spacing"> <strong>Note: </strong>The video in this demo was taken after the test mode of Firebase expired, so the Add to favorites function is not working since documents are not being written anymore in the collection, but it does work in production mode.</p>
        <div class="container">
            <my-video :sources="video.sources" :options="video.options"></my-video>
        </div>

    </div>
</template>

<script>

    import myVideo from 'vue-video'

    export default {
        layout: "normal",
        components: {
            myVideo
        },
        head(){
            return {
            title: "Freelance UX/UI Designer and Frontend Web Developer"
            }
        },
        data() {
            return {
                banner: require('~/assets/banner3.svg'),
                image1: require('~/assets/image20.png'),
                image2: require('~/assets/image21.png'),
                image3: require('~/assets/image22.png'),
                image4: require('~/assets/image23.png'),
                image5: require('~/assets/image24.png'),
                video: {
                    sources: [{
                        src: require('~/assets/demo.mp4'),
                        type: 'video/mp4'
                    }]
                }
            }
        },
    }
</script>

<style scoped>
.header{
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.tucausa{
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin-left: 15%;
    margin-right: 15%;
    font-family: 'Nunito', sans-serif;
    margin-bottom: 24px;
}
.banner{
    max-height: 250px;
    margin: 20px 0;
}
.titulo{
    margin-top: 24px;
}
.spacing{
    margin-bottom: 24px;
}
.image{
    width: 100%;
    border-radius: 12px;
}
.image3{
    max-width: 250px;
}
    @media screen and (max-width: 769px) {
        .tucausa{
            margin: 0 24px;
        }
        .banner{
            width: 100%;
        }
        .spacing{
            margin-bottom: 20px;
        }
        .header{
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .image{
            width: 100%;
            border-radius: 8px;
        }
        .wireframes{
            display: flex;
            flex-direction: column;
        }
    }
</style>